name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Cloudflare WARP
      uses: Boostport/setup-cloudflare-warp@v1
      with:
        organization: "leaflex.site"
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Read package name from package.json
      id: package_name
      run: echo "PACKAGE_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          dkr-reg.home.leaflex.site/${{ env.PACKAGE_NAME }}:latest
          dkr-reg.home.leaflex.site/${{ env.PACKAGE_NAME }}:${{ env.SHORT_SHA }}
        outputs: type=registry

    - name: Disconnect Cloudflare WARP
      run: warp-cli disconnect